### ISSUE TITLE
Is this correct ? Specifications seems to speak about 7 bytes

### ISSUE THREAD

**Issue by lpatiny** [octanis-instruments/uavcan#1]
https://github.com/cheminfo/uavcan/blob/master/src/parser/__tests__/parse.NodeStatus.js#L9

**Comment by bitmorse** [comment]
the 8th byte is the tail byte that you need to have for distinguishing transfers. it is present in all payloads. the transfer_payload is the actual data.
[transfer_payload=[byte0, byte1, byte2, byte3, byte4, byte5, byte6], tail = [byte7] ]
https://uavcan.org/Specification/4._CAN_bus_transport_layer/

**Comment by lpatiny** [comment]
If I understand well this is related to the reconstruction of larger packets that 7 bytes but it seems to me that when we call the parser we should give the full data (even if split on many packets) and therefore remove this 8th byte that is only useful for assembly.
